[versions]
androidxTest = "1.5.0"
androidxArchCoreTesting = "2.2.0"
androidxFragmentTesting = "1.5.5"
androidxTestRunner = "1.5.2"
androidxTestRules = "1.4.0"
androidxTestJunit = "1.1.5"
androidxTruth = "1.5.0"
espresso = "3.5.1"
mock = "1.13.5"
truth = "1.1.3"

[libraries]
androidx-arch-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidxArchCoreTesting" }
androidx-fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "androidxFragmentTesting" }
androidx-testing = { group = "androidx.test", name = "core", version.ref = "androidxTest" }
androidx-test-junitext = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestJunit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-truthext = { group = "androidx.test.ext", name = "truth", version.ref = "androidxTruth" }
androidx-test-espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-test-espressoContrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
androidx-test-espressoIntents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso" }
androidx-test-espressoAccessibility = { group = "androidx.test.espresso", name = "espresso-accessibility", version.ref = "espresso" }
androidx-test-espressoWeb = { group = "androidx.test.espresso", name = "espresso-web", version.ref = "espresso" }
androidx-test-espressoConcurrent = { group = "androidx.test.espresso.idling", name = "idling-concurrent", version.ref = "espresso" }
androidx-test-espressoIdlingResource = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espresso" }
googletruth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
mock = { module = "io.mockk:mockk", version.ref = "mock" }
robolectric = { module = "org.robolectric:robolectric", version = "4.9" }